# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-LangPrefCookie
version:      1.02
version_from: lib/Apache/LangPrefCookie.pm
installdirs:  site
requires:
    Apache:                        0
    Apache::Cookie:                0
    Apache::Request:               0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
